[project]
name = "mcp_servers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gradio[mcp]>=5.30.0",
    "mcp[cli]>=1.9.2",
]
